### PR TITLE
fix templates added subpage_base and home_base

### LINKED ISSUE #124: update student home template/ui to match other apps

### PR DESCRIPTION
**Pull request by oceancypress**
test: check all pages have styling and javascript functionality

Closes #124 #140 #125 #117

### CODE REVIEW

**Comment by oceancypress** [comment]
plz hold, need to merge develop

**Review by jeffreicher — COMMENTED** [review]
code review looks good - have no live tested on branch

**Comment by oceancypress** [comment]
Ready!

**Review by bjmckenz — APPROVED** [review]
LGTM.

**Pull request merged**
